# TCL File Generated by Component Editor 16.0
# Sun Mar 05 14:42:34 EST 2017
# DO NOT MODIFY


# 
# lda_hw_interface "lda_hw_interface" v1.0
#  2017.03.05.14:42:34
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module lda_hw_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME lda_hw_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "MY IP CORES"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME lda_hw_interface
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL lab5_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lab5_interface.sv SYSTEM_VERILOG PATH lab5_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL lab5_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file lab5_interface.sv SYSTEM_VERILOG PATH lab5_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clockreset
set_interface_property s1 associatedReset clockreset_reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_chipselect chipselect Input 1
add_interface_port s1 avs_s1_address address Input 3
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_waitrequest waitrequest Output 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ledr
# 
add_interface ledr conduit end
set_interface_property ledr associatedClock ""
set_interface_property ledr associatedReset ""
set_interface_property ledr ENABLED true
set_interface_property ledr EXPORT_OF ""
set_interface_property ledr PORT_NAME_MAP ""
set_interface_property ledr CMSIS_SVD_VARIABLES ""
set_interface_property ledr SVD_ADDRESS_GROUP ""

add_interface_port ledr coe_ledr_export_LEDR export Output 10


# 
# connection point vgar
# 
add_interface vgar conduit end
set_interface_property vgar associatedClock ""
set_interface_property vgar associatedReset ""
set_interface_property vgar ENABLED true
set_interface_property vgar EXPORT_OF ""
set_interface_property vgar PORT_NAME_MAP ""
set_interface_property vgar CMSIS_SVD_VARIABLES ""
set_interface_property vgar SVD_ADDRESS_GROUP ""

add_interface_port vgar coe_vgar_export_VGA_R export Output 10


# 
# connection point vgag
# 
add_interface vgag conduit end
set_interface_property vgag associatedClock ""
set_interface_property vgag associatedReset ""
set_interface_property vgag ENABLED true
set_interface_property vgag EXPORT_OF ""
set_interface_property vgag PORT_NAME_MAP ""
set_interface_property vgag CMSIS_SVD_VARIABLES ""
set_interface_property vgag SVD_ADDRESS_GROUP ""

add_interface_port vgag coe_vgag_export_VGA_G export Output 10


# 
# connection point vgab
# 
add_interface vgab conduit end
set_interface_property vgab associatedClock ""
set_interface_property vgab associatedReset ""
set_interface_property vgab ENABLED true
set_interface_property vgab EXPORT_OF ""
set_interface_property vgab PORT_NAME_MAP ""
set_interface_property vgab CMSIS_SVD_VARIABLES ""
set_interface_property vgab SVD_ADDRESS_GROUP ""

add_interface_port vgab coe_vgab_export_VGA_B export Output 10


# 
# connection point vgahs
# 
add_interface vgahs conduit end
set_interface_property vgahs associatedClock ""
set_interface_property vgahs associatedReset ""
set_interface_property vgahs ENABLED true
set_interface_property vgahs EXPORT_OF ""
set_interface_property vgahs PORT_NAME_MAP ""
set_interface_property vgahs CMSIS_SVD_VARIABLES ""
set_interface_property vgahs SVD_ADDRESS_GROUP ""

add_interface_port vgahs coe_vgahs_export_VGA_HS export Output 1


# 
# connection point vgavs
# 
add_interface vgavs conduit end
set_interface_property vgavs associatedClock ""
set_interface_property vgavs associatedReset ""
set_interface_property vgavs ENABLED true
set_interface_property vgavs EXPORT_OF ""
set_interface_property vgavs PORT_NAME_MAP ""
set_interface_property vgavs CMSIS_SVD_VARIABLES ""
set_interface_property vgavs SVD_ADDRESS_GROUP ""

add_interface_port vgavs coe_vgavs_export_VGA_VS export Output 1


# 
# connection point vgablank
# 
add_interface vgablank conduit end
set_interface_property vgablank associatedClock ""
set_interface_property vgablank associatedReset ""
set_interface_property vgablank ENABLED true
set_interface_property vgablank EXPORT_OF ""
set_interface_property vgablank PORT_NAME_MAP ""
set_interface_property vgablank CMSIS_SVD_VARIABLES ""
set_interface_property vgablank SVD_ADDRESS_GROUP ""

add_interface_port vgablank coe_vgablank_export_VGA_BLANK_N export Output 1


# 
# connection point vgasync
# 
add_interface vgasync conduit end
set_interface_property vgasync associatedClock ""
set_interface_property vgasync associatedReset ""
set_interface_property vgasync ENABLED true
set_interface_property vgasync EXPORT_OF ""
set_interface_property vgasync PORT_NAME_MAP ""
set_interface_property vgasync CMSIS_SVD_VARIABLES ""
set_interface_property vgasync SVD_ADDRESS_GROUP ""

add_interface_port vgasync coe_vgasync_export_VGA_SYNC_N export Output 1


# 
# connection point vgaclk
# 
add_interface vgaclk conduit end
set_interface_property vgaclk associatedClock ""
set_interface_property vgaclk associatedReset ""
set_interface_property vgaclk ENABLED true
set_interface_property vgaclk EXPORT_OF ""
set_interface_property vgaclk PORT_NAME_MAP ""
set_interface_property vgaclk CMSIS_SVD_VARIABLES ""
set_interface_property vgaclk SVD_ADDRESS_GROUP ""

add_interface_port vgaclk coe_vgaclk_export_VGA_CLK export Output 1


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true
set_interface_property clockreset EXPORT_OF ""
set_interface_property clockreset PORT_NAME_MAP ""
set_interface_property clockreset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset SVD_ADDRESS_GROUP ""

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true
set_interface_property clockreset_reset EXPORT_OF ""
set_interface_property clockreset_reset PORT_NAME_MAP ""
set_interface_property clockreset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset_reset SVD_ADDRESS_GROUP ""

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1

